-- =============================================================================
-- RENFI - SCRIPT MAESTRO DE CONFIGURACIÓN DE BASE DE DATOS (SUPABASE / POSTGRESQL)
-- Proyecto: Renfi Mobile (Expo Go) + Web (Angular) + API Backend
-- Compatible al 100% con Supabase (SQL Editor y PostgREST API)
-- =============================================================================
-- INSTRUCCIONES:
-- 1. Abre tu proyecto en Supabase (https://supabase.com/dashboard)
-- 2. Ve a la sección "SQL Editor" en el menú lateral izquierdo
-- 3. Crea una "New Query", pega todo el contenido de este archivo y presiona "Run"
-- 4. ¡Listo! Todas las tablas, procedimientos almacenados, permisos (GRANT) y
--    datos de prueba (seed) quedarán configurados de inmediato.
-- =============================================================================

-- =============================================================================
-- 1. EXTENSIONES
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 2. CREACIÓN DE TABLAS (IDENTIFICADORES PASCALCASE)
-- =============================================================================

-- Tabla: Rol
CREATE TABLE IF NOT EXISTS public."Rol" (
    "IdRol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreRol" VARCHAR(300) NOT NULL
);

-- Tabla: Usuario
CREATE TABLE IF NOT EXISTS public."Usuario" (
    "NumeroDocumento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdRol" INT REFERENCES public."Rol"("IdRol") ON UPDATE CASCADE ON DELETE SET NULL,
    "NombreUsuario" VARCHAR(300) NOT NULL,
    "ApellidoUsuario" VARCHAR(300) NOT NULL,
    "Telefono" VARCHAR(100),
    "Contrasena" VARCHAR(300) NOT NULL,
    "Correo" VARCHAR(500) NOT NULL UNIQUE,
    "Estado" VARCHAR(150) DEFAULT 'Activo'
);

-- Tabla: Municipio
CREATE TABLE IF NOT EXISTS public."Municipio" (
    "IdMunicipio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreMunicipio" VARCHAR(150) NOT NULL
);

-- Tabla: Finca
CREATE TABLE IF NOT EXISTS public."Finca" (
    "IdFinca" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdMunicipio" INT REFERENCES public."Municipio"("IdMunicipio") ON UPDATE CASCADE ON DELETE SET NULL,
    "NumeroDocumentoUsuario" INT REFERENCES public."Usuario"("NumeroDocumento") ON UPDATE CASCADE ON DELETE SET NULL,
    "NombreFinca" VARCHAR(300) NOT NULL,
    "Direccion" VARCHAR(500),
    "InformacionAdicional" VARCHAR(500),
    "Capacidad" INT DEFAULT 1,
    "Precio" INT DEFAULT 0,
    "Estado" VARCHAR(150) DEFAULT 'Disponible',
    "Calificacion" INT DEFAULT 5
);

-- Tabla: Imagen
CREATE TABLE IF NOT EXISTS public."Imagen" (
    "IdImagen" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UrlImagen" VARCHAR(500) NOT NULL,
    "IdFinca" INT REFERENCES public."Finca"("IdFinca") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Tabla: MetodoDePago
CREATE TABLE IF NOT EXISTS public."MetodoDePago" (
    "IdMetodoDePago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreMetodoDePago" VARCHAR(150) NOT NULL,
    "PagoMixto" BOOLEAN DEFAULT FALSE
);

-- Tabla: Reserva
CREATE TABLE IF NOT EXISTS public."Reserva" (
    "IdReserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdFinca" INT REFERENCES public."Finca"("IdFinca") ON UPDATE CASCADE ON DELETE CASCADE,
    "NumeroDocumentoUsuario" INT REFERENCES public."Usuario"("NumeroDocumento") ON UPDATE CASCADE ON DELETE SET NULL,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "Estado" VARCHAR(150) DEFAULT 'Pendiente',
    "MontoReserva" INT DEFAULT 0
);

-- Tabla: Factura
CREATE TABLE IF NOT EXISTS public."Factura" (
    "IdFactura" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdReserva" INT REFERENCES public."Reserva"("IdReserva") ON UPDATE CASCADE ON DELETE CASCADE,
    "FechaFactura" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "Total" INT DEFAULT 0
);

-- Tabla: Pago
CREATE TABLE IF NOT EXISTS public."Pago" (
    "IdPago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdFactura" INT REFERENCES public."Factura"("IdFactura") ON UPDATE CASCADE ON DELETE CASCADE,
    "IdMetodoDePago" INT REFERENCES public."MetodoDePago"("IdMetodoDePago") ON UPDATE CASCADE ON DELETE SET NULL,
    "Monto" INT DEFAULT 0,
    "FechaPago" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "EstadoPago" VARCHAR(150) DEFAULT 'Pendiente'
);

-- Índices de búsqueda
CREATE INDEX IF NOT EXISTS "idx_usuario_correo" ON public."Usuario"("Correo");
CREATE INDEX IF NOT EXISTS "idx_usuario_rol" ON public."Usuario"("IdRol");
CREATE INDEX IF NOT EXISTS "idx_finca_municipio" ON public."Finca"("IdMunicipio");
CREATE INDEX IF NOT EXISTS "idx_finca_usuario" ON public."Finca"("NumeroDocumentoUsuario");
CREATE INDEX IF NOT EXISTS "idx_imagen_finca" ON public."Imagen"("IdFinca");
CREATE INDEX IF NOT EXISTS "idx_reserva_finca" ON public."Reserva"("IdFinca");
CREATE INDEX IF NOT EXISTS "idx_reserva_usuario" ON public."Reserva"("NumeroDocumentoUsuario");
CREATE INDEX IF NOT EXISTS "idx_factura_reserva" ON public."Factura"("IdReserva");
CREATE INDEX IF NOT EXISTS "idx_pago_factura" ON public."Pago"("IdFactura");
CREATE INDEX IF NOT EXISTS "idx_pago_metodo" ON public."Pago"("IdMetodoDePago");

-- =============================================================================
-- 3. PROCEDIMIENTOS Y FUNCIONES ALMACENADAS (PL/pgSQL - SUPABASE RPC)
-- =============================================================================

--------------------------------------------------------------------------------
-- 3.1 ROL
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public."SP_ListarRol"()
RETURNS TABLE (
    "IdRol" INT,
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT r."IdRol", r."NombreRol"
    FROM public."Rol" r
    ORDER BY r."IdRol" ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_InsertarRol"(
    "p_NombreRol" VARCHAR(300)
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Rol" ("NombreRol")
    VALUES ("p_NombreRol")
    RETURNING "IdRol" INTO v_id;
    RETURN v_id;
END;
$$;

--------------------------------------------------------------------------------
-- 3.2 USUARIOS Y AUTENTICACIÓN
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public."SP_ListarUsuarios"()
RETURNS TABLE (
    "NumeroDocumento" INT,
    "NombreUsuario" VARCHAR(300),
    "ApellidoUsuario" VARCHAR(300),
    "Telefono" VARCHAR(100),
    "Correo" VARCHAR(500),
    "Contrasena" VARCHAR(300),
    "Estado" VARCHAR(150),
    "IdRol" INT,
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u."NumeroDocumento",
        u."NombreUsuario",
        u."ApellidoUsuario",
        u."Telefono",
        u."Correo",
        u."Contrasena",
        u."Estado",
        r."IdRol",
        COALESCE(r."NombreRol", 'Sin Rol')
    FROM public."Usuario" u
    LEFT JOIN public."Rol" r ON u."IdRol" = r."IdRol"
    ORDER BY u."NumeroDocumento" ASC;
END;
$$;

-- Registrar usuario (retorna NumeroDocumento generado)
CREATE OR REPLACE FUNCTION public."SP_RegistrarUsuario"(
    "p_IdRol" INT DEFAULT 2,
    "p_NombreUsuario" VARCHAR(300) DEFAULT '',
    "p_ApellidoUsuario" VARCHAR(300) DEFAULT '',
    "p_Telefono" VARCHAR(100) DEFAULT NULL,
    "p_Correo" VARCHAR(300) DEFAULT '',
    "p_Contrasena" VARCHAR(300) DEFAULT '',
    "p_Estado" VARCHAR(150) DEFAULT 'Activo'
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Usuario" (
        "IdRol", "NombreUsuario", "ApellidoUsuario", "Telefono", "Correo", "Contrasena", "Estado"
    ) VALUES (
        COALESCE("p_IdRol", 2), 
        "p_NombreUsuario", 
        "p_ApellidoUsuario", 
        "p_Telefono", 
        LOWER(TRIM("p_Correo")), 
        "p_Contrasena", 
        COALESCE("p_Estado", 'Activo')
    )
    RETURNING "NumeroDocumento" INTO v_id;
    RETURN v_id;
END;
$$;

-- Iniciar sesión
CREATE OR REPLACE FUNCTION public."SP_IniciarSesion"(
    "p_Correo" VARCHAR(500),
    "p_Contrasena" VARCHAR(300)
)
RETURNS TABLE (
    "NumeroDocumento" INT,
    "IdRol" INT,
    "NombreUsuario" VARCHAR(300),
    "ApellidoUsuario" VARCHAR(300),
    "Telefono" VARCHAR(100),
    "Correo" VARCHAR(500),
    "Estado" VARCHAR(150),
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u."NumeroDocumento",
        u."IdRol",
        u."NombreUsuario",
        u."ApellidoUsuario",
        u."Telefono",
        u."Correo",
        u."Estado",
        COALESCE(r."NombreRol", 'Cliente') AS "NombreRol"
    FROM public."Usuario" u
    LEFT JOIN public."Rol" r ON u."IdRol" = r."IdRol"
    WHERE LOWER(TRIM(u."Correo")) = LOWER(TRIM("p_Correo"))
      AND u."Contrasena" = "p_Contrasena"
      AND u."Estado" = 'Activo';
END;
$$;

--------------------------------------------------------------------------------
-- 3.3 MUNICIPIOS
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public."SP_ListarMunicipios"()
RETURNS TABLE (
    "IdMunicipio" INT,
    "NombreMunicipio" VARCHAR(150)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT m."IdMunicipio", m."NombreMunicipio"
    FROM public."Municipio" m
    ORDER BY m."NombreMunicipio" ASC;
END;
$$;

--------------------------------------------------------------------------------
-- 3.4 FINCAS
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public."SP_ListarFincas"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "Direccion" VARCHAR(500),
    "InformacionAdicional" VARCHAR(500),
    "Capacidad" INT,
    "Precio" INT,
    "Estado" VARCHAR(150),
    "Calificacion" INT,
    "IdMunicipio" INT,
    "NombreMunicipio" VARCHAR(150),
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300),
    "TelefonoPropietario" VARCHAR(100),
    "CorreoPropietario" VARCHAR(500)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca",
        f."Direccion",
        f."InformacionAdicional",
        f."Capacidad",
        f."Precio",
        f."Estado",
        f."Calificacion",
        m."IdMunicipio",
        COALESCE(m."NombreMunicipio", 'Antioquia') AS "NombreMunicipio",
        u."NumeroDocumento" AS "IdPropietario",
        COALESCE(u."NombreUsuario", 'Anfitrión') AS "NombrePropietario",
        COALESCE(u."ApellidoUsuario", 'Renfi') AS "ApellidoPropietario",
        u."Telefono" AS "TelefonoPropietario",
        u."Correo" AS "CorreoPropietario"
    FROM public."Finca" f
    LEFT JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    LEFT JOIN public."Usuario" u ON f."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY f."IdFinca" ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_InsertarFinca"(
    "p_IdMunicipio" INT,
    "p_NumeroDocumentoUsuario" INT,
    "p_NombreFinca" VARCHAR(300),
    "p_Direccion" VARCHAR(500),
    "p_InformacionAdicional" VARCHAR(500),
    "p_Capacidad" INT,
    "p_Precio" INT,
    "p_Estado" VARCHAR(150) DEFAULT 'Disponible',
    "p_Calificacion" INT DEFAULT 5
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Finca" (
        "IdMunicipio", "NumeroDocumentoUsuario", "NombreFinca", "Direccion", 
        "InformacionAdicional", "Capacidad", "Precio", "Estado", "Calificacion"
    ) VALUES (
        "p_IdMunicipio", "p_NumeroDocumentoUsuario", "p_NombreFinca", "p_Direccion", 
        "p_InformacionAdicional", "p_Capacidad", "p_Precio", COALESCE("p_Estado", 'Disponible'), COALESCE("p_Calificacion", 5)
    )
    RETURNING "IdFinca" INTO v_id;
    RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_ModificarFinca"(
    "p_IdFinca" INT,
    "p_IdMunicipio" INT,
    "p_NombreFinca" VARCHAR(300),
    "p_Direccion" VARCHAR(500),
    "p_InformacionAdicional" VARCHAR(500),
    "p_Capacidad" INT,
    "p_Precio" INT,
    "p_Estado" VARCHAR(150),
    "p_Calificacion" INT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public."Finca"
    SET
        "IdMunicipio" = COALESCE("p_IdMunicipio", "IdMunicipio"),
        "NombreFinca" = COALESCE("p_NombreFinca", "NombreFinca"),
        "Direccion" = COALESCE("p_Direccion", "Direccion"),
        "InformacionAdicional" = COALESCE("p_InformacionAdicional", "InformacionAdicional"),
        "Capacidad" = COALESCE("p_Capacidad", "Capacidad"),
        "Precio" = COALESCE("p_Precio", "Precio"),
        "Estado" = COALESCE("p_Estado", "Estado"),
        "Calificacion" = COALESCE("p_Calificacion", "Calificacion")
    WHERE "IdFinca" = "p_IdFinca";
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_EliminarFinca"(
    "p_IdFinca" INT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM public."Finca"
    WHERE "IdFinca" = "p_IdFinca";
END;
$$;

--------------------------------------------------------------------------------
-- 3.5 RESERVAS, PAGOS Y FACTURAS
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public."SP_ListarReservas"()
RETURNS TABLE (
    "IdReserva" INT,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "Estado" VARCHAR(150),
    "MontoReserva" INT,
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "NombreMunicipio" VARCHAR(150),
    "NumeroDocumentoUsuario" INT,
    "NombreCliente" VARCHAR(300),
    "ApellidoCliente" VARCHAR(300),
    "CorreoCliente" VARCHAR(500)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        r."IdReserva",
        r."FechaReserva",
        r."FechaEntrada",
        r."FechaSalida",
        r."Estado",
        r."MontoReserva",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        m."NombreMunicipio",
        u."NumeroDocumento" AS "NumeroDocumentoUsuario",
        u."NombreUsuario" AS "NombreCliente",
        u."ApellidoUsuario" AS "ApellidoCliente",
        u."Correo" AS "CorreoCliente"
    FROM public."Reserva" r
    LEFT JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    LEFT JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    LEFT JOIN public."Usuario" u ON r."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY r."IdReserva" DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_ListarReservasPorUsuario"(
    "p_NumeroDocumentoUsuario" INT
)
RETURNS TABLE (
    "IdReserva" INT,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "Estado" VARCHAR(150),
    "MontoReserva" INT,
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "NombreMunicipio" VARCHAR(150),
    "NumeroDocumentoUsuario" INT,
    "NombreCliente" VARCHAR(300),
    "ApellidoCliente" VARCHAR(300),
    "CorreoCliente" VARCHAR(500)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        r."IdReserva",
        r."FechaReserva",
        r."FechaEntrada",
        r."FechaSalida",
        r."Estado",
        r."MontoReserva",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        m."NombreMunicipio",
        u."NumeroDocumento" AS "NumeroDocumentoUsuario",
        u."NombreUsuario" AS "NombreCliente",
        u."ApellidoUsuario" AS "ApellidoCliente",
        u."Correo" AS "CorreoCliente"
    FROM public."Reserva" r
    LEFT JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    LEFT JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    LEFT JOIN public."Usuario" u ON r."NumeroDocumentoUsuario" = u."NumeroDocumento"
    WHERE r."NumeroDocumentoUsuario" = "p_NumeroDocumentoUsuario"
    ORDER BY r."IdReserva" DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_CrearReserva"(
    "p_IdFinca" INT,
    "p_NumeroDocumentoUsuario" INT,
    "p_FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "p_FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "p_MontoReserva" INT,
    "p_IdMetodoDePago" INT DEFAULT 1,
    "p_Estado" VARCHAR(150) DEFAULT 'Confirmada'
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id_reserva INT;
    v_id_factura INT;
BEGIN
    INSERT INTO public."Reserva" (
        "IdFinca", "NumeroDocumentoUsuario", "FechaEntrada", "FechaSalida", "Estado", "MontoReserva"
    ) VALUES (
        "p_IdFinca", "p_NumeroDocumentoUsuario", "p_FechaEntrada", "p_FechaSalida", 
        COALESCE("p_Estado", 'Confirmada'), "p_MontoReserva"
    )
    RETURNING "IdReserva" INTO v_id_reserva;

    INSERT INTO public."Factura" ("IdReserva", "Total")
    VALUES (v_id_reserva, "p_MontoReserva")
    RETURNING "IdFactura" INTO v_id_factura;

    INSERT INTO public."Pago" ("IdFactura", "IdMetodoDePago", "Monto", "EstadoPago")
    VALUES (v_id_factura, COALESCE("p_IdMetodoDePago", 1), "p_MontoReserva", 'Pagado');

    RETURN v_id_reserva;
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_ActualizarEstadoReserva"(
    "p_IdReserva" INT,
    "p_NuevoEstado" VARCHAR(150)
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public."Reserva"
    SET "Estado" = "p_NuevoEstado"
    WHERE "IdReserva" = "p_IdReserva";
END;
$$;

CREATE OR REPLACE FUNCTION public."SP_ListarMetodosDePago"()
RETURNS TABLE (
    "IdMetodoDePago" INT,
    "NombreMetodoDePago" VARCHAR(150),
    "PagoMixto" BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT mp."IdMetodoDePago", mp."NombreMetodoDePago", mp."PagoMixto"
    FROM public."MetodoDePago" mp
    ORDER BY mp."IdMetodoDePago" ASC;
END;
$$;

-- =============================================================================
-- 4. CONFIGURACIÓN DE SEGURIDAD (ROW LEVEL SECURITY Y PERMISOS DE ACCESO)
-- =============================================================================
ALTER TABLE public."Rol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Usuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Municipio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Finca" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Imagen" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."MetodoDePago" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Reserva" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Factura" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Pago" ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura y escritura abiertas para clientes de Renfi
DROP POLICY IF EXISTS "Permitir_Todo_Rol" ON public."Rol";
CREATE POLICY "Permitir_Todo_Rol" ON public."Rol" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Usuario" ON public."Usuario";
CREATE POLICY "Permitir_Todo_Usuario" ON public."Usuario" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Municipio" ON public."Municipio";
CREATE POLICY "Permitir_Todo_Municipio" ON public."Municipio" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Finca" ON public."Finca";
CREATE POLICY "Permitir_Todo_Finca" ON public."Finca" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Imagen" ON public."Imagen";
CREATE POLICY "Permitir_Todo_Imagen" ON public."Imagen" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_MetodoDePago" ON public."MetodoDePago";
CREATE POLICY "Permitir_Todo_MetodoDePago" ON public."MetodoDePago" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Reserva" ON public."Reserva";
CREATE POLICY "Permitir_Todo_Reserva" ON public."Reserva" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Factura" ON public."Factura";
CREATE POLICY "Permitir_Todo_Factura" ON public."Factura" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir_Todo_Pago" ON public."Pago";
CREATE POLICY "Permitir_Todo_Pago" ON public."Pago" FOR ALL USING (true) WITH CHECK (true);

-- Permisos fundamentales para los roles 'anon', 'authenticated' y 'service_role'
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

-- =============================================================================
-- 5. DATOS DE SEMILLA (SEED DATA)
-- =============================================================================

-- Roles
INSERT INTO public."Rol" ("IdRol", "NombreRol") VALUES 
(1, 'Administrador'),
(2, 'Cliente'),
(3, 'Propietario')
ON CONFLICT ("IdRol") DO UPDATE SET "NombreRol" = EXCLUDED."NombreRol";

SELECT setval(pg_get_serial_sequence('public."Rol"', 'IdRol'), COALESCE(MAX("IdRol"), 1)) FROM public."Rol";

-- Municipios de Antioquia
INSERT INTO public."Municipio" ("IdMunicipio", "NombreMunicipio") VALUES
(1, 'Medellín'),
(2, 'Guatapé'),
(3, 'Santa Fe de Antioquia'),
(4, 'Jardín'),
(5, 'Jericó'),
(6, 'Rionegro'),
(7, 'El Peñol'),
(8, 'Barbosa'),
(9, 'Girardota'),
(10, 'Copacabana'),
(11, 'San Jerónimo'),
(12, 'La Ceja')
ON CONFLICT ("IdMunicipio") DO UPDATE SET "NombreMunicipio" = EXCLUDED."NombreMunicipio";

SELECT setval(pg_get_serial_sequence('public."Municipio"', 'IdMunicipio'), COALESCE(MAX("IdMunicipio"), 1)) FROM public."Municipio";

-- Métodos de Pago
INSERT INTO public."MetodoDePago" ("IdMetodoDePago", "NombreMetodoDePago", "PagoMixto") VALUES
(1, 'Efectivo', false),
(2, 'Transferencia Bancaria', false),
(3, 'Tarjeta de Crédito', false),
(4, 'Nequi / Daviplata', true)
ON CONFLICT ("IdMetodoDePago") DO UPDATE SET "NombreMetodoDePago" = EXCLUDED."NombreMetodoDePago", "PagoMixto" = EXCLUDED."PagoMixto";

SELECT setval(pg_get_serial_sequence('public."MetodoDePago"', 'IdMetodoDePago'), COALESCE(MAX("IdMetodoDePago"), 1)) FROM public."MetodoDePago";

-- Usuarios Demo (contraseñas en texto plano compatibles con frontend)
INSERT INTO public."Usuario" ("NumeroDocumento", "IdRol", "NombreUsuario", "ApellidoUsuario", "Telefono", "Contrasena", "Correo", "Estado") VALUES
(1, 1, 'Admin', 'Renfi', '3001234567', 'admin123', 'admin@renfi.com', 'Activo'),
(2, 2, 'Juan', 'Pérez', '3109876543', 'cliente123', 'juan.perez@example.com', 'Activo'),
(3, 2, 'Cliente', 'Demo', '3114567890', 'cliente123', 'cliente@renfi.com', 'Activo')
ON CONFLICT ("Correo") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Usuario"', 'NumeroDocumento'), COALESCE(MAX("NumeroDocumento"), 1)) FROM public."Usuario";

-- Fincas Demo
INSERT INTO public."Finca" ("IdFinca", "IdMunicipio", "NumeroDocumentoUsuario", "NombreFinca", "Direccion", "InformacionAdicional", "Capacidad", "Precio", "Estado", "Calificacion") VALUES
(1, 2, 1, 'Finca Campestre El Paraíso', 'Km 5 Vía El Peñol - Guatapé', 'Hermosa finca colonial frente a la represa, muelle privado, jacuzzi climatizado, zona BBQ y amplios corredores con chambranas tradicionales.', 16, 850000, 'Disponible', 5),
(2, 3, 1, 'Villa Los Samanes de Santa Fe', 'Vereda El Espinal, Santa Fe de Antioquia', 'Clima cálido garantizado, piscina olímpica privada, palmeras, kiosco campestre y amplias áreas verdes para descanso familiar.', 20, 1200000, 'Disponible', 5),
(3, 6, 1, 'Hacienda La Cordillera', 'Vereda Las Cuchillas, Rionegro', 'Exclusiva hacienda cafetera tradicional con vista panorámica a la cordillera, chimenea de leña, senderos y arquitectura en madera noble.', 12, 950000, 'Disponible', 5),
(4, 4, 1, 'Cabaña El Cafetal de Jardín', 'Camino a La Herradura, Jardín', 'Auténtica arquitectura andina rodeada de cafetales y orquídeas. Balcón perimetral con vistas a los majestuosos Farallones.', 8, 450000, 'Disponible', 5),
(5, 5, 1, 'Refugio de Jericó', 'Vereda Castocá, Jericó', 'Tranquilidad absoluta, amaneceres entre la niebla montañera, senderos ecológicos y ambiente acogedor de tapia pisada.', 10, 580000, 'Disponible', 5),
(6, 11, 1, 'Hacienda San Jerónimo del Sol', 'Sector La Loma, San Jerónimo', 'Piscina con cascada, cancha deportiva, salón de juegos y zona de hamacas bajo frondosos árboles frutales.', 25, 1500000, 'Disponible', 5)
ON CONFLICT ("IdFinca") DO UPDATE SET
    "NombreFinca" = EXCLUDED."NombreFinca",
    "Direccion" = EXCLUDED."Direccion",
    "InformacionAdicional" = EXCLUDED."InformacionAdicional",
    "Capacidad" = EXCLUDED."Capacidad",
    "Precio" = EXCLUDED."Precio",
    "Estado" = EXCLUDED."Estado",
    "Calificacion" = EXCLUDED."Calificacion";

SELECT setval(pg_get_serial_sequence('public."Finca"', 'IdFinca'), COALESCE(MAX("IdFinca"), 1)) FROM public."Finca";

-- Imágenes Demo para cada Finca
INSERT INTO public."Imagen" ("IdImagen", "IdFinca", "UrlImagen") VALUES
(1, 1, 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80'),
(2, 2, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'),
(3, 3, 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80'),
(4, 4, 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'),
(5, 5, 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80'),
(6, 6, 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80')
ON CONFLICT ("IdImagen") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Imagen"', 'IdImagen'), COALESCE(MAX("IdImagen"), 1)) FROM public."Imagen";

-- =============================================================================
-- FIN DEL SCRIPT DE CONFIGURACIÓN
-- =============================================================================

